version: 2
jobs:
  build:
    working_directory: ~/ark-core
    docker:
      - image: node:9
      - image: redis:alpine
      - image: postgres:alpine
        environment:
          POSTGRES_PASSWORD: password
          POSTGRES_DB: ark_testnet
          POSTGRES_USER: ark
    steps:
      - checkout
      - run:
          name: Install yarn 
          command: 'curl -o- -L https://yarnpkg.com/install.sh | bash && export PATH="$HOME/.yarn/bin:$PATH" && yarn config set cache-folder $HOME/.cache/yarn'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install packages
          command: yarn
  test:
    docker:
      - image: node:9
      - image: redis:alpine
      - image: postgres:alpine
        environment:
          POSTGRES_PASSWORD: password
          POSTGRES_DB: ark_testnet
          POSTGRES_USER: ark
    steps:
      - checkout
      - run:
          name: Test
          command: yarn test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              only: ci