version: 2
jobs:
  build:
    working_directory: ~/ark-core
    docker:
      - image: node:9
      - image: redis:alpine
      - image: postgres:alpine
        environment:
          POSTGRES_PASSWORD: password
          POSTGRES_DB: ark_testnet
          POSTGRES_USER: ark
    steps:
      - checkout
      - run:
          name: Apt update
          command: 'echo "deb http://ftp.debian.org/debian stable main contrib non-free" >> /etc/apt/sources.list && apt-get update'
      - run:
          name: Install xsel
          command: 'apt-get install -q xsel'
      - run:
          name: Install yarn 
          command: 'curl -o- -L https://yarnpkg.com/install.sh | bash && export PATH="$HOME/.yarn/bin:$PATH" && yarn config set cache-folder $HOME/.cache/yarn'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install packages
          command: yarn
      - run:
          name: Test
          command: ./node_modules/.bin/cross-env ARK_ENV=test ./node_modules/.bin/jest --detectOpenHandles --runInBand

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
